### ISSUE TITLE
Simulate a Double Press on Home Button

### ISSUE THREAD

**Issue by jochasinga** [joemasilotti/UI-Testing-Cheat-Sheet#16]
I'm trying to simulate double pressing the home button to launch the so-called app switcher. However, it looks like `- (void)pressButton:(XCUIDeviceButton)button;` is not synchronous and calling 

```Objective-C

[[XCUIDevice sharedDevice] pressButton:XCUIDeviceButtonHome];

```

would launch the home screen any way regardless of how quick the subsequent press follows. Any idea or tips on how to accomplish this?

**Comment by stanly-johnson** [comment]
It is not possible to do so. Refer here : https://discussions.apple.com/thread/4907752?start=0&tstart=0

**Comment by jakovljevic-mladen** [comment]
@stanly-johnson This link you provided is related to UIAutomation framework which is not related to this project.

**Comment by jochasinga** [comment]
@stanly-johnson the thread didn't really convince me that it was not possible.

**Comment by stanly-johnson** [comment]
Sorry for the wrong link above. But I  don't think its possible programmatically. https://stackoverflow.com/questions/14024058/how-to-replicate-home-button-double-tap-effect-on-click-of-a-button

Apple does not allow the said functionality, unless you figure out some kind of workaround which I'm excited to hear about.

**Comment by jakovljevic-mladen** [comment]
I'm sorry @stanly-johnson, but this link is also not related to this issue: the SO question is about whether it is possible to programmatically open recent app screen directly from the app (just like you'd double-tap the home button), but is not related to UI testing framework and how to do it in this framework.

**Comment by jochasinga** [comment]
@stanly-johnson the home button function can be called with XCtest framework https://developer.apple.com/documentation/xctest/xcuidevice.button/1619047-home. The issue is one cannot calling it twice to simulate a double tap which usually calls app switcher / multitasking view in later iOS because the API is intentionally asynchronous (the first call does not wait).

**Comment by joemasilotti** [comment]
### This comment, from 2017, is no longer correct. See [this comment](https://github.com/joemasilotti/UI-Testing-Cheat-Sheet/issues/16#issuecomment-672845180).

<details>
  <summary>View the out of date comment.</summary>
  
Here's what I found after digging into this issue:

* It is _not_ possible to switch out of the app-under-test with "normal" XCUITest framework APIs.
* Even if we could, **the framework doesn't have access to anything outside of the app-under-test. That means if we switch to Safari.app we won't be able to tap or query the UI.**
* Due to this limitation the only thing switching out could test is what happens when you switch *back in*.

If you _really_ need to test this behavior I recommend adding code to your app that manually triggers this process and then is called from test. Of course, this is far from ideal. But in my opinion this is an edge case that honestly shouldn't be tested via this framework.
</details>

**Comment by superz515** [comment]
@joemasilotti It is possible. Inspired by an old answer in this [thread](https://developer.apple.com/forums/thread/38973), after tons of trying and failing, I finally figured out a way to support multitasking in UITesting on iOS 13.

Please check out my repository here: https://github.com/superz515/UITestingMultitaskingHelper.

**Comment by joemasilotti** [comment]
Thanks for following up on this! My comment in 2017 is no longer correct and I've edited it to reflect that.

You can now launch apps directly and launch the springboard directly with UI Testing. I have an example on how to open Safari.app in my latest blog post, [How to test deep links with UI Testing](https://masilotti.com/test-deep-links-with-ui-testing/). As @jochasinga mentions, we still can't double tap the home button. But launching an app explicitly should solve your issue.

```swift
let safari = XCUIApplication(bundleIdentifier: "com.apple.mobilesafari")
safari.launch()
XCTAssert(safari.wait(for: .runningForeground, timeout: 5))
```

I will be adding this to the cheat sheet soon, stay tuned!
