### ISSUE TITLE
How to test specific view controller

### ISSUE THREAD

**Issue by hamedaakhlaghi** [joemasilotti/UI-Testing-Cheat-Sheet#21]
It seems all of the tests you write must start from the beginning, I want to write a class for testing specific view controller, without any action on another screen, Is there any solution?

**Comment by kenji21** [comment]
You wan't to do "Unit tests" with view controllers (more like integration tests), you can do it, but you have to make a "TestingAppDelegate" that does nothing, and you can inject it in main.swift:

```swift
let appDelegateClass: AnyClass = NSClassFromString("AppTests.TestingAppDelegate") ?? AppDelegate.self
let argv = UnsafeMutableRawPointer(CommandLine.unsafeArgv).bindMemory(to: UnsafeMutablePointer<Int8>.self, capacity: Int(CommandLine.argc))
UIApplicationMain(CommandLine.argc,
                  argv,
                  nil,
                  NSStringFromClass(appDelegateClass))
```

Then, during you "view controllers tests", simply create a new window and set your view controller to its rootViewController property

The big limitation is that you can no more use "app.staticTexts" because there is no access to XCUI* (app is an instance of XCUIApplication) classes in unit tests, this is where [KIF](https://github.com/kif-framework/KIF) can help you.

**Comment by jakovljevic-mladen** [comment]
There is one hack that you could use to test any ViewController you like in your UI tests. It is not recommended way though, but could be useful. I explained one method [here](https://stackoverflow.com/a/49044442/1253279). You can adopt it in your project by following this idea.

**Comment by joemasilotti** [comment]
As the others have mentioned, this isn't currently possible without some hacks or additional application code. I'm going to close this issue until something changes in the framework.
