### ISSUE TITLE
Question - Do you run all of the tests at one time or run them individually

### ISSUE THREAD

**Issue by ghost** [joemasilotti/UI-Testing-Cheat-Sheet#4]
Thanks so much for the information you provide on UI Testing and XCode 7.  I have found it very useful in helping me learn how to write UI Tests.

I have seen several notes that tests should be stand alone.  I downloaded this Volley project and if I run the tests individually - one at a time, they all work.  But If I try to run all of them starting at the top, only one or two of them will pass. 

So would it be better to run the tests one at a time in general?

Thanks

**Comment by joemasilotti** [comment]
Thanks, glad it's helping you learn!

I've started to experience this issue as well. The tests kept failing because the app hadn't officially terminated. 

I am am now [explicitly terminating the app after each test](https://github.com/joemasilotti/UI-Testing-Cheat-Sheet/commit/a1a1f139c7de10d19012de7959da57862a4d0137) is run. Please pull down the latest code and try again. Also, ensure that you are running Xcode 7.1.1 from the App Store.

**Comment by ghost** [comment]
Thanks so much.  I pulled down the latest code and now all the tests run as expected
